#!/bin/bash

source libjira.sh

function hello() {
	echo "jiracmd 0.1"
}

function prompt() {
	echo -n "jira # "
}

function print_help() {
	echo -e "Available commands:"
	echo -e "\tlist_versions"
	echo -e "\tlist_components"
	echo -e "\tcreate_version <name>"
	echo -e "\tdelete_version <name>"
	echo -e "\tcreate_component <name> <description>"
	echo -e "\tdelete_component <name>"
	echo -e "\tget_issue <key>"
	echo -e "\tlist_status <name>"
	echo -e "\tsearch <jql>"
	echo -e "\tlist_transitions <key>"
}

function bye() {
	echo -n "bye!"
}

if [ "$1" = "-i" ] ; then
	# interactive shell
	
	hello && prompt

	while read LINE ; do
		case "${LINE}" in
			"help")
				print_help
			;;
			"quit")
				bye && exit 0
			;;
			*)
				eval "${LINE}"
			;;
		esac
		prompt
	done
else
	# non interactive
	eval $*
fi
